### ISSUE TITLE
Double Pull Request

### ISSUE THREAD

**Issue by rach-m** [soleilyasmina/gaia#7]
**Situation:** Student makes PR before they are ready and does not realize PR will update so they close PR. They then open a new PR for homework submission.

**Issue:** When pulling down HW to grade, the student's work is cloned and then removed due to the two pull requests: one open and one closed.

**Comment by soleilyasmina** [comment]
Hey Rach!

Can you make this issue ticket on the enterprise repo? I'm happy to handle it there.
